tutorial3/polls/urls.py
from django.conf.urls import url
from . import views


app_name= 'polls'

urlpatterns = [
    url(r'^$',views.IndexView.as_view(),name='index'),
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view(),name='detail'),
    url(r'^(?P<question_id>[0-9]+)/vote/$',views.vote,name='vote'),
    url(r'^(?P<pk>[0-9]+)/results/$',views.ResultsView.as_view(),name='results'),
]

tutorial3/tutorial3/urls.py
from django.conf.urls import url,include
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^polls/',include('polls.urls')),
    ]

tutorial3/polls/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.utils.encoding  import python_2_unicode_compatible
from django.db import models


# Create your models here.
@python_2_unicode_compatible
class Question(models.Model):
    question_text=models.CharField(max_length=200)
    pub_date= models.DateTimeField(auto_now_add=True,auto_now=False)

    def __str__(self):
        return " %s was published on  %s "%(self.question_text, self.pub_date)

@python_2_unicode_compatible
class Choice(models.Model):
    question= models.ForeignKey(Question,on_delete=models.CASCADE)
    choice= models.CharField(max_length=200)
    vote = models.IntegerField(default=0)

    def __str__(self):
        return self.choice

tutorial3/polls/views.py
from __future__ import unicode_literals
from django.http import HttpResponse,HttpResponseRedirect
from .models import Question,Choice
from django.shortcuts import render,get_object_or_404
from django.urls import reverse
from django.views import generic


# Import the render function to directly load,request,template_name, context manager
# Importing the Question class from the models

from django.template import loader
# The django template loader to load the template into the program

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.all()

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'


def vote(request,question_id):
    question = get_object_or_404(Question,pk=question_id)
    try:
        selected_choice= question.choice_set.get(pk=request.POST['choice'])
    except (KeyError,Choice.DoesNotExist):
        # return it to display form
        context= {"question":question,
                  "error_message":"You didn't select a choice",}
        return render(request,'polls/detail.html',context)
    else:
        selected_choice.vote +=1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results',args=(question.id,)))

tutorial3/polls/templates/polls/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body><h2>{{question.question_text}}</h2>

{% if error_message %}
<p> <strong>  {{error_message}} </strong> </p>
{% endif %}
<form action="{% url 'polls:vote' question.id %}" method="post" >
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}">
    <label  for="choice{{forloop.counter}}"> {{choice.choice}} </label>
    <br>
    {% endfor %}

<input type="submit" value="vote">
</form>








</body>
</html>

tutorial3/polls/templates/polls/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<ul>
{% for q in question_list %}
    <li>   {{q.question_text}}   </li>
{% endfor %}
</ul>
</body>
</html>

tutorial3/polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<h1>     {{question.question_text}}   </h1>

<ul>
    {% for choice in question.choice_set.all%}
  <li> {{choice.choice}} --- {{choice.vote}}  vote{{choice.vote|pluralize}}           </li>
    {%endfor%}

</ul>

<a href="{% url 'polls:detail' question.id%}">
Vote again?</a>





</body>
</html>